### ISSUE TITLE
Remove emojis from the title

### ISSUE THREAD

**Issue by VDK** [toolforge/video2commons#101]
Example of YouTube video with Emojis in the title: https://youtube.com/watch?v=DqF0OP_Zpxo

**Comment by zhuyifei1999** [comment]
Sorry for the last response. I found a library to match emojis:
```
>>> emoji.get_emoji_regexp().sub('', u'Verandering begint klein 💚 | GroenLinks Campagnevideo | PS2019')
u'Verandering begint klein  | GroenLinks Campagnevideo | PS2019'
```
However, if I do the replacement like above, we are left with both spaces next to the emoji. Would you prefer that, or, do some complex magic? Example scenarios to consider:
```
Have spacing / no spacing
* 💚foo bar
* 💚 foo bar
* foo bar💚
* foo bar 💚
* foo💚bar
* foo 💚bar
* foo💚 bar
* foo 💚 bar

Multi spacing / unequal spacing
* foo 💚   bar 

Multiple emoji
* foo 💚 💚 bar
* foo 💚💚 bar
* foo💚 💚bar
```

How should the spacing be handled after the emojis are removed?

**Comment by VDK** [comment]
double spaces should be turned into a single space

**Comment by zhuyifei1999** [comment]
By that do you mean any sequence of two or more spaces should be replaces by a single space, regardless of whether it was next to an emoji?

**Comment by VDK** [comment]
Wel, yes, Commons doesn't like it when there are two spaces in a filename

**Comment by zhuyifei1999** [comment]
No more emojis: https://tools.wmflabs.org/video2commons/#!https://youtube.com/watch?v=DqF0OP_Zpxo
