### ISSUE TITLE
Error: An exception occurred: IOError: [Errno 116] Stale file handle

### ISSUE THREAD

**Issue by nicolas-raoul** [toolforge/video2commons#102]
Thanks for this very promising tool!

I am trying to contribute a 700 MB mp4 video that I took.
After the upload, I entered the metadata, and pressed "Next". result:

> Error: An exception occurred: IOError: [Errno 116] Stale file handle

![Screenshot from 2019-05-30 12-41-04](https://user-images.githubusercontent.com/99590/58606901-6a54cd00-82d8-11e9-97b0-c6cae640929c.png)

After the upload is finished, what is the time limit that I have to write metadata and press Next? Only a few minutes had past.

Ideally:
- I should be asked to write and confirm metadata **while** the upload+conversion is happening.
- Conversion and final publication on Commons should happen automatically after the upload finishes, **without waiting for me to push a button**. Having "OK" buttons in the middle of the process wastes the time of the user and may lead to various timeout errors.

Thanks :-)

**Comment by zhuyifei1999** [comment]
> Error: An exception occurred: IOError: [Errno 116] Stale file handle

There was an NFS maintenance recently, and I have since restarted the webservice. Could you check if it has been fixed?

> After the upload is finished, what is the time limit that I have to write metadata and press Next?

I think it is one or two days IIRC.

> Ideally:

Good point, Though that would be very hard to implement this workflow (even UW upload first). Could you file a seperate ticket about this?

**Comment by zhuyifei1999** [comment]
I'm closing this one; feel free to reopen if 'Stale file handle' exception occurs again
