### ISSUE TITLE
Allow prefilling file info & etc

### ISSUE THREAD

**Issue by dkmgfk** [toolforge/video2commons#104]
At the moment we can only add the descriptions etc after the file's upload, which is not exactly convienent.
Also it would be nice to allow batch uploading in a fashion simmilar to Upload Wizard.
Hardware acceleration may be used for higher quality, more efficient video conversion, as Intel has released SDK with VP9 encoding support back in 2018.
Sometimes upload would fail half way for some reason (I suspect it's about internet connection), in this case the reuploading procedure will reupload everything, without utilizing the chuncks which have been already uploaded to some tmp folder in the server.
There should be a prompt when closing the tab during uploading, as Upload Wizard and Wikipedia editor.

Cheers

**Comment by dkmgfk** [comment]
Or external AMD video cards, I should say.

Additionally the subititles can't be imported automatically as far as I can tell.

**Comment by dkmgfk** [comment]
Also IPv6 is still not supported on the wmflabs.org server, even in 2019

**Comment by zhuyifei1999** [comment]
One ticket per request, thanks.

> At the moment we can only add the descriptions etc after the file's upload, which is not exactly convienent.

#103

>  Also it would be nice to allow batch uploading in a fashion simmilar to Upload Wizard.

#48

> Hardware acceleration may be used for higher quality, more efficient video conversion, as Intel has released SDK with VP9 encoding support back in 2018.
> Or external AMD video cards, I should say.

Not possible. The video drivers are proprietary and [we cannot install them](https://wikitech.wikimedia.org/wiki/Wikitech:Cloud_Services_Terms_of_use#What_uses_of_Cloud_Services_do_we_not_like?)

> Sometimes upload would fail half way for some reason (I suspect it's about internet connection), in this case the reuploading procedure will reupload everything, without utilizing the chuncks which have been already uploaded to some tmp folder in the server.

What is the error message? Is this upload about you -> v2c or v2c -> commons? Please file under a separate ticket.

>  There should be a prompt when closing the tab during uploading, as Upload Wizard and Wikipedia editor.

Please file under a separate ticket.

> Additionally the subititles can't be imported automatically as far as I can tell.

Looks like a bug to me. What are the steps to reproduce this issue? Please file under a separate ticket.

> Also IPv6 is still not supported on the wmflabs.org server, even in 2019

[Not something I can fix](https://phabricator.wikimedia.org/T37947)

**Comment by dkmgfk** [comment]
> Additionally the subititles can't be imported automatically as far as I can tell.

Oh this is due to my misunderstanding. I supposed it to import subtitles from the video files I uploaded. But it's actually for importing subtitles from websites like YouTube.

Importing subtitles automatically is not possible because there are so many different kinds of subtitles that can be embedded to a MP4 or MKV file. The subtitles in my case are bitmaps.
