### ISSUE TITLE
TypeError while deleting a task

### ISSUE THREAD

**Issue by acagastya** [toolforge/video2commons#109]
Steps to reproduce:
1. Add a task, let it finish
2. Try removing the completed task

Following message appears in the alert box:
`An exception occurred: TypeError: lrem() takes exactly 4 arguments (3 given)`

**Comment by acagastya** [comment]
@zhuyifei1999 Yet to be deployed?

**Comment by zhuyifei1999** [comment]
Yes, I'm currently deploying it.

**Comment by zhuyifei1999** [comment]
Ok should be deployed now. Could you retry?

**Comment by acagastya** [comment]
@zhuyifei1999 Seems to be working.  Thank you for fixing it!
