### ISSUE TITLE
Stale file handle

### ISSUE THREAD

**Issue by sikanderiqbal** [toolforge/video2commons#113]
After uploading a file and adding description text, clicking Next shows this error in Firefox and Chrome:

> Error: An exception occurred: IOError: [Errno 116] Stale file handle

**Comment by zhuyifei1999** [comment]
Probably wrecked by recent network maintenance. I just restarted all services. Did that help?

**Comment by sikanderiqbal** [comment]
Yes, that worked and the file is processing now. Thank you.
