### ISSUE TITLE
HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by elisfkc** [toolforge/video2commons#119]
I keep getting the "HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug" error. I tried it a month ago and got this error, and I still am getting this error now. I have tried it on two different Windows computers, using mostly Chrome but also Firefox.

The full text of the message is "Error: An exception occurred: DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

**Comment by chicocvenancio** [comment]
See https://phabricator.wikimedia.org/T236446 YouTube has blocked video2commons. 

WMF [has stated](https://phabricator.wikimedia.org/T236446#5883909) it would work on a long-term solution to import creative commons videos from YouTube with their teams.
