### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by pieva** [toolforge/video2commons#121]
Current output connecting to https://video2commons.toolforge.org/ :
---
Please file an issue in GitHub: Traceback (most recent call last): File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request() File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request return self.finalize_request(rv) File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 1969, in finalize_request response = self.process_response(response) File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/flask/app.py", line 2268, in process_response self.session_interface.save_session(self, ctx.session, response) File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/redisession.py", line 89, in save_session self.redis.delete(self.prefix + session.sid) File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/redis/client.py", line 1293, in delete return self.execute_command('DEL', *names) File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command conn = self.connection or pool.get_connection(command_name, **options) File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/redis/connection.py", line 1073, in get_connection connection.connect() File "/data/project/video2commons/www/python/venv/local/lib/python2.7/site-packages/redis/connection.py", line 544, in connect raise ConnectionError(self._error_message(e)) ConnectionError: Error 111 connecting to video-redis-buster.video.eqiad.wmflabs:6379. Connection refused.

**Comment by jidanni** [comment]
Users coming from https://commons.wikimedia.org/wiki/Commons:Video#Uploading_a_video get this message.
Also noted on https://phabricator.wikimedia.org/T261245 .

**Comment by zhuyifei1999** [comment]
Rebooted by andrew.
