### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by satdeepgill** [toolforge/video2commons#125]
Video2Commons is not working and gives the following error message when I tried uploading a video from Youtube: 

Error: An exception occurred: DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by davidhicks** [comment]
Duplicate of #110
