### ISSUE TITLE
Guess language error with YouTube

### ISSUE THREAD

**Issue by gabeclasson** [toolforge/video2commons#142]
Whenever I try to use the tool with a YouTube URL, I get the following error as soon as I click "next" on the first dialog box: 

Error: An exception occurred: AttributeError: b"module 'guess_language' has no attribute 'guessLanguage'"

**Comment by gabeclasson** [comment]
Is anyone else experiencing this? It seems that the guess_language module has broken and it is no longer being maintained. See here: https://github.com/kent37/guess-language/issues/12

Perhaps we can just switch to [`guess_language-spirit`](https://pypi.org/project/guess_language-spirit/), which appears to be a fork of this package.

**Comment by gabeclasson** [comment]
To see what I mean, use these two test cases:

- https://www.youtube.com/watch?v=Ci7P9uVHkYQ (Succeeds because description is shorter than 100 characters, so it bypasses trying to guess a language for it)
- https://www.youtube.com/watch?v=JsLwRaVmSoo (Fails because description is longer than 100 characters, so it tries to guess the language but fails because the guess-language package is no longer maintained and is broken.)

**Comment by axel-wilke** [comment]
I'm trying to use https://video2commons.toolforge.org/ to upload & convert a video from Vimeo to Wikimedia Commons and get the exact same error. Interesting that this happens on different platforms.

**Comment by gabeclasson** [comment]
> I'm trying to use https://video2commons.toolforge.org/ to upload & convert a video from Vimeo to Wikimedia Commons and get the exact same error. Interesting that this happens on different platforms.

It happens on different platforms because video2commons puts all media descriptions through the same process to guess what language they are.

**Comment by chicocvenancio** [comment]
I had only deployed the fixes on the backend. All should be good now.

**Comment by gabeclasson** [comment]
I am still getting a similar error: 

 `Error: An exception occurred: AttributeError: b"module 'guess_language' has no attribute 'guess_language'"`

I can tell that you deployed the fixes because the error now refers to attribute `guess_language` instead of attribute `guessLanguage`. 

Here's my theory for why this error may still be persisting:

Since guess_language-spirit and guess_language are both referenced using the name `guess_language` in code, is it possible that the old guess_language package is still installed and the ambiguity in the package name has been resolved by using the old package?
