### ISSUE TITLE
Opus encoding broken

### ISSUE THREAD

**Issue by zhuyifei1999** [toolforge/video2commons#15]
Need some testing

**Comment by zhuyifei1999** [comment]
The problem: opus encoder doesn't seem to allow constant quality,

**Comment by veikk0** [comment]
Also note that Opus upsamples everything to a sample rate of 48000 KHz and stores to original value, so the decoder can resample and play it at the correct sample rate. So not only is changing the sample rate unnecessary, it's also unsupported. Trying to use the `-ar` switch in FFmpeg when encoding Opus results in an error: `[libopus @ 0x5621d7ee4d20] Specified sample rate 44100 is not supported`. Unless the value is 48000 of course, which will work, but that's the same as not using the switch in the first place.

From reading around the 'net it also seems that constant quality is the default operating mode of Opus but the quality values are mapped directly to bitrate and called using the bitrate setting. As opposed to encoders like libvorbis and LAME that have a more abstracted CQ mode which still [results in a certain bitrate within a small range.](https://trac.ffmpeg.org/wiki/Encode/MP3)

According to [HydrogenAudio's wiki](https://wiki.hydrogenaud.io/index.php?title=Opus) 128kbps is very close to transparency for music and 160-192kbps is transparent with a very low chance for artifacts. 128k would probably be fine but AFAIK Youtube does Opus encodes up to 160k.

**Comment by zhuyifei1999** [comment]
Thanks. How much bitrate do you think we should use? I'm thinking of 128k

**Comment by veikk0** [comment]
128k sounds good to me. No pun intended.
