### ISSUE TITLE
Error: Unable to extract uploader id

### ISSUE THREAD

**Issue by butko** [toolforge/video2commons#161]
On any video from YouTube video2commons write error: An exception occurred: DownloadError: b'ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'

**Comment by chicocvenancio** [comment]
Fixed in #162
