### ISSUE TITLE
Stuck on "Loading..." indefinitely.

### ISSUE THREAD

**Issue by Laqueesha** [toolforge/video2commons#163]
Stuck on "Loading..." indefinitely. Tried Chrome, Edge, and Firefox. Even tried my phone's mobile browser. None work.

Following messages in console:

index.js:83 [Report Only] Refused to connect to 'wss://video2commons-socketio.toolforge.org/socket.io/?EIO=3&transport=websocket&sid=gIE9oHIJOD2eK0GAAAAO' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' 'unsafe-inline' blob: data: filesystem: mediastream: *.toolforge.org wikibooks.org *.wikibooks.org wikidata.org *.wikidata.org wikimedia.org *.wikimedia.org wikinews.org *.wikinews.org wikipedia.org *.wikipedia.org wikiquote.org *.wikiquote.org wikisource.org *.wikisource.org wikiversity.org *.wikiversity.org wikivoyage.org *.wikivoyage.org wiktionary.org *.wiktionary.org *.wmcloud.org *.wmflabs.org wikimediafoundation.org mediawiki.org *.mediawiki.org wss://video2commons.toolforge.org". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
/favicon.ico:1 

Failed to load resource: the server responded with a status of 500 ()

Content Security Policy: The page’s settings observed the loading of a resource at wss://video2commons-socketio.toolforge.org/socket.io/?EIO=3&transport=websocket&sid=wU1GQKrEoU9e-SQIAAL0 (“default-src”). A CSP report is being sent. 

Cookie “v2c-session” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it.

 index.js:83 [Report Only] Refused to connect to 'wss://video2commons-socketio.toolforge.org/socket.io/?EIO=3&transport=websocket&sid=bUNGulxKYfDkwhLOAAMf' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' 'unsafe-inline' blob: data: filesystem: mediastream: *.toolforge.org wikibooks.org *.wikibooks.org wikidata.org *.wikidata.org wikimedia.org *.wikimedia.org wikinews.org *.wikinews.org wikipedia.org *.wikipedia.org wikiquote.org *.wikiquote.org wikisource.org *.wikisource.org wikiversity.org *.wikiversity.org wikivoyage.org *.wikivoyage.org wiktionary.org *.wiktionary.org *.wmcloud.org *.wmflabs.org wikimediafoundation.org mediawiki.org *.mediawiki.org wss://video2commons.toolforge.org". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

[Report Only] Refused to connect to 'wss://video2commons-socketio.toolforge.org/socket.io/?EIO=3&transport=websocket&sid=YHXys9-FCGrykhuAAAS_' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' 'unsafe-inline' blob: data: filesystem: mediastream: *.toolforge.org wikibooks.org *.wikibooks.org wikidata.org *.wikidata.org wikimedia.org *.wikimedia.org wikinews.org *.wikinews.org wikipedia.org *.wikipedia.org wikiquote.org *.wikiquote.org wikisource.org *.wikisource.org wikiversity.org *.wikiversity.org wikivoyage.org *.wikivoyage.org wiktionary.org *.wiktionary.org *.wmcloud.org *.wmflabs.org wikimediafoundation.org mediawiki.org *.mediawiki.org wss://video2commons.toolforge.org". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by Laqueesha** [comment]
Working for me as of 18 June 2023. Weird. Hopefully it stays working!

**Comment by chicocvenancio** [comment]
Finally figured the likely source of this. Fixed in #180
