### ISSUE TITLE
V2C down

### ISSUE THREAD

**Issue by Yannf** [toolforge/video2commons#181]
I got this, and someone else too: https://commons.wikimedia.org/wiki/Commons_talk:Video2commons#V2C_down

`Please file an issue in GitHub: Traceback (most recent call last): File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request return self.finalize_request(rv) File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1540, in finalize_request response = self.process_response(response) File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1888, in process_response self.session_interface.save_session(self, ctx.session, response) File "/data/project/video2commons/www/python/src/../../../video2commons/frontend/redisession.py", line 89, in save_session self.redis.delete(self.prefix + session.sid) File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 1567, in delete return self.execute_command('DEL', *names) File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command return self.parse_response(conn, command_name, **options) File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response response = connection.read_response() File "/data/project/video2commons/www/python/venv/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response raise response redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.`

**Comment by vprivat-ads** [comment]
There is an alert on [Grafana](https://grafana.wmcloud.org/d/0g9N-7pVz/cloud-vps-project-board?orgId=1&var-project=video&var-instance=All&from=now-15m&to=now&refresh=5s):

![image](https://github.com/toolforge/video2commons/assets/146961743/42e7a6ac-b8c8-489b-83ec-67db5a19fb40)

**Comment by chicocvenancio** [comment]
I've resized the redis instance to reduce the issues. Until #176 is figured out its likely to still have a few errors.
