### ISSUE TITLE
MaybeEncodingError import of module

### ISSUE THREAD

**Issue by Yannf** [toolforge/video2commons#184]
Hi, Another error now :((( while trying to upload [https://www.youtube.com/watch?v=Zmj_6JjE5gc].

`An exception occurred: MaybeEncodingError: b'(\'\\\'PicklingError("Can\\\\\\\'t pickle <class \\\\\\\'video2commons.exceptions.TaskError\\\\\\\'>: import of module \\\\\\\'video2commons.exceptions\\\\\\\' failed")\\\'\', \'\\\'(1, <ExceptionInfo: TaskError(b"pywikibot.Error: UploadError: exists-normalized: File exists with different extension as \\\\\\\'Z\\\\\\\\xc3\\\\\\\\xa9ro_de_conduite_(1933)_par_Jean_Vigo.jpg\\\\\\\'.")>, None)\\\'\')'`

**Comment by Yannf** [comment]
Again while uploading https://archive.org/details/dixiana-4-k This is a big file (3.5 GB), but...
`An exception occurred: MaybeEncodingError: b'(\'\\\'PicklingError("Can\\\\\\\'t pickle <class \\\\\\\'video2commons.exceptions.TaskError\\\\\\\'>: import of module \\\\\\\'video2commons.exceptions\\\\\\\' failed")\\\'\', \'"(1, <ExceptionInfo: TaskError(\\\'/mnt/nfs/labstore-secondary-project/gentoo-prefix/usr/bin/ffmpeg -y -i /srv/v2c/output/bcd9bb16ad0148a1/dl.mp4 -max_muxing_queue_size 4096 -threads 16 -row-mt 1 -crf 20 -qmin 1 -qmax 51 -b:v 0 -vcodec libvpx-vp9 -tile-columns 4 -auto-alt-ref 1 -lag-in-frames 25 -f webm -ss 0 -b:a 128000 -ar 48000 -acodec libopus -pass 2 -passlogfile /srv/v2c/output/bcd9bb16ad0148a1/dl.mp4.vp9.webm.log /srv/v2c/output/bcd9bb16ad0148a1/dl.mp4.vp9.webm\\\\\\\\nExitcode: 153\\\')>, None)"\')'`

**Comment by chicocvenancio** [comment]
this is ffmpeg exiting with 153 code. Not quite sure how to debug that.

**Comment by chicocvenancio** [comment]
These are all different errors. This latest one is `pywikibot.Error: APIError: stashfailed: Could not acquire lock. Somebody else is doing something to this file.` which is a commons api error, might have luck retrying by the error message.

**Comment by don-vip** [comment]
Old ticket that mixes different problems partially solved with the recent upgrade, closing. Please open new tickets if some problems remain that are not covered by an existing ticket.
