### ISSUE TITLE
internal_api_error_UploadChunkFileException

### ISSUE THREAD

**Issue by Yannf** [toolforge/video2commons#204]
I got this message `An exception occurred: MaybeEncodingError: b'(\'\\\'PicklingError("Can\\\\\\\'t pickle <class \\\\\\\'video2commons.exceptions.TaskError\\\\\\\'>: import of module \\\\\\\'video2commons.exceptions\\\\\\\' failed")\\\'\', \'"(1, <ExceptionInfo: TaskError(b\\\'pywikibot.Error: APIMWError: internal_api_error_UploadChunkFileException: [3bdb04b1-a5e9-4095-bf21-e514e20d4d18] Caught exception of type UploadChunkFileException\\\\\\\\n[errorclass: UploadChunkFileException;\\\\\\\\n servedby: mw-api-ext.eqiad.main-7b8678458b-kxhx5]\\\')>, None)"\')'` for https://archive.org/details/back-to-gods-country-1919-by-david-hartford

Should I restart the task?

**Comment by don-vip** [comment]
New code deployed, can you please try again?

**Comment by Yannf** [comment]
This one uploaded fine.

**Comment by Yannf** [comment]
I got this again. while trying to upload a new version of https://commons.wikimedia.org/wiki/File:The_Daughter_of_Dawn_(1920)_by_Norbert_A._Myles.webm

`00126: FAILED: internal_api_error_UploadChunkFileException: [d6ae6783-305c-4360-aaf8-74550a9728b7] Caught exception of type UploadChunkFileException`

index.php?action=raw&ctype=text/javascript&title=User:Rillke/MwJSBot.js&_=2:1136 mwbot> uploadstash-exception: Could not store upload in the stash (UploadStashFileException): "An unknown error occurred in storage backend "local-swift-codfw".".  {"error":{"code":"uploadstash-exception","info":"Could not store upload in the stash (UploadStashFileException): \"An unknown error occurred in storage backend \"local-swift-codfw\".\".","*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw-api-ext.codfw.main-7bdb7bf5cd-7tv9z"}
fail @ index.php?action=raw&ctype=text/javascript&title=User:Rillke/MwJSBot.js&_=2:1136Understand this errorAI
index.php?action=raw&ctype=text/javascript&title=User:Rillke/MwJSBot.js&_=2:1136 mwbot> uploadstash-exception: Could not store upload in the stash (UploadStashFileException): "An unknown error occurred in storage backend "local-swift-codfw".".  {"error":{"code":"uploadstash-exception","info":"Could not store upload in the stash (UploadStashFileException): \"An unknown error occurred in storage backend \"local-swift-codfw\".\".","*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw-api-ext.codfw.main-7bdb7bf5cd-x9fxt"}
fail @ index.php?action=raw&ctype=text/javascript&title=User:Rillke/MwJSBot.js&_=2:1136Understand this errorAI
index.php?action=raw&ctype=text/javascript&title=User:Rillke/MwJSBot.js&_=2:1136 mwbot> internal_api_error_UploadChunkFileException: [d6ae6783-305c-4360-aaf8-74550a9728b7] Caught exception of type UploadChunkFileException  {"error":{"code":"internal_api_error_UploadChunkFileException","info":"[d6ae6783-305c-4360-aaf8-74550a9728b7] Caught exception of type UploadChunkFileException","errorclass":"UploadChunkFileException"},"servedby":"mw-api-ext.codfw.main-7bdb7bf5cd-f7wl8"}
