### ISSUE TITLE
Do not create Phabricator tasks tagged with Wikimedia-Site-requests and Commons

### ISSUE THREAD

**Issue by aklapper** [toolforge/video2commons#207]
`video2commons/frontend/static/video2commons.js` currently sets `projects: 'Wikimedia-Site-requests,commons,video2commons,server-side-upload-request'` but these tasks are not relevant for anyone watching the Commons workboard in Phabricator and these tasks are  no side requests as they are no configuration changes. Please remove these two project tags. Thanks!

**Comment by aklapper** [comment]
See e.g. https://phabricator.wikimedia.org/T369340

**Comment by don-vip** [comment]
Thank you. I've fixed the issue, it will be part of the planned general update of the entire infratructure (this week if all goes well)
