### ISSUE TITLE
Worker exited prematurely: signal 15

### ISSUE THREAD

**Issue by Yannf** [toolforge/video2commons#209]
3 files failed with `An exception occurred: WorkerLostError: b'Worker exited prematurely: signal 15 (SIGTERM) Job: 61.'`

https://archive.org/details/sir-arnes-treasure-1919-by-mauritz-stiller
https://archive.org/details/zander-the-great-1925-by-george-w.-hill
https://archive.org/details/our-hospitality-1923-by-buster-keaton-and-john-g.-blystone

**Comment by Yannf** [comment]
All these uploaded fine on 2nd run.

**Comment by don-vip** [comment]
OK I think it's because the platform was not fully stable until yesterday, let's close this one.
