### ISSUE TITLE
Content too short

### ISSUE THREAD

**Issue by wilfredor** [toolforge/video2commons#26]
<img src='http://i.imgur.com/KL3GaR6.png' />

**Comment by zhuyifei1999** [comment]
https://github.com/rg3/youtube-dl/search?q=content+too+short&type=Issues&utf8=%E2%9C%93

Just give a few reties.

**Comment by zhuyifei1999** [comment]
rg3/youtube-dl@a3c3a1e was [deployed](https://tools.wmflabs.org/sal/video?d=2017-08-26) a few days ago. This should be hopefully fixed.
