### ISSUE TITLE
Avoid to lost the information wrote when you click out the box

### ISSUE THREAD

**Issue by ivanhercaz** [toolforge/video2commons#90]
_video2commons_ is an excellent tool to upload videos to Commons, but I have a problem with it. Sometimes, when I are in the step to name the file and fill the description page, I click outside the box without noticing and, suddenly, I have lost all I wrote... When I click again in add task I have to begin the process again from zero.

Could you make anything to solve it?

Thanks in advance!

Regards, Ivanhercaz

**Comment by zhuyifei1999** [comment]
Hmm. Should the new form reuse the previous information, if any?

**Comment by distriker** [comment]
Yes, something like you say @zhuyifei1999 could be a good solution. Sometimes I click out by error and if I have write a good description and you lose it, it demotivate me a bit... If some user want to reset the information, the useful way could be add a "reset" button, but no the way of click out the box.

**Comment by zhuyifei1999** [comment]
Uh, two questions:
* When the new modal opens, do you prefer to go back to first step or the step when the modal is closed?
* Should data be reused even if they are not saved/submitted? (i.e. neither back nor next are pressed before closing)

The current code does not distinguish between a modal close based by clicking cancel or by clicking outside the modal, but I think I can find a way to workaround it.

**Comment by ivanhercaz** [comment]
Hi @zhuyifei1999! Sorry for the delay, I was busy this days.
* I would prefer the step in which the user was when the modal was closed.
* Yes, the data should be reused. I think is preferable to save it rather than lose it, because if you don't want the same data, you have only to delete/discard what you wrote.

If you discover the way to develop correctly this, it could improve the app. Thank you for your effort!

**Comment by zhuyifei1999** [comment]
Hmm... I'm thinking about the 'reset' button and running into a dilemma here: if the button is shown only when the step != 'source' (first step), replacing the 'cancel' button dynamically, the button must be disabled during input processing to avoid race conditions; but when the input processing hangs (such as when my wifi driver fails) where would be no way to exit the modal. On the other hand, if we have both 'reset' and 'cancel' that would be quite a clutter. :(
Anther idea would be to save the data only when clicking 'out the box', and 'cancel' would mean 'reset' and 'hide model'. Alternatively we could also make clicking 'out the box' do nothing, which may be easiest to do.
Which one do you think is the best?
