### ISSUE TITLE
Android browser thinks links to the uploaded videos are direct links to video files 

### ISSUE THREAD

**Issue by VDK** [toolforge/video2commons#92]
This triggers a download prompt
![screenshot_20171128-214408](https://user-images.githubusercontent.com/849603/33343517-dd451eb2-d485-11e7-8306-f098ed71374b.jpg)

**Comment by zhuyifei1999** [comment]
The relevant html on v2c is `<a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm">Studenten wonen boven azc Stieltjesstraat.webm</a>`.

Would [Studenten wonen boven azc Stieltjesstraat.webm](https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm) also trigger a download prompt?

**Comment by zhuyifei1999** [comment]
Also, any of the links in https://tools.wmflabs.org/yifeibot/v2ci92.html not trigger a download prompt? Source:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
  <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
  <title>video2commons Issue #92 Test</title>
</head>
<body>
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm">Studenten wonen boven azc Stieltjesstraat.webm</a><br>
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm">No ext in text</a><br>
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm" download>Force download</a><br>
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm" type="text/html; charset=UTF-8">Set type attr</a><br>
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm" target="_self">Set target=_self</a><br>
</body>
</html>
```

**Comment by VDK** [comment]
All trigger the prompt :(

**Comment by VDK** [comment]
It's weird because I don't get this anywhere else, like within Commons

<code>
<a href="/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">Studenten wonen boven azc Stieltjesstraat.webm<a></code>

**Comment by zhuyifei1999** [comment]
I copied three links to https://tools.wmflabs.org/yifeibot/v2ci92.html:
```
  <a href="/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a>
  <a href="//commons.wikimedia.org/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a>
  <a href="https://commons.wikimedia.org/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a>
```
First is path-relative, second is protocol-relative, third is absolute. Do any of them work?

**Comment by VDK** [comment]
Second and third work!

**Comment by zhuyifei1999** [comment]
That would be a weird bug in android browser :(. I guess I'll make the url protocol-relative then.

**Comment by zhuyifei1999** [comment]
Uh, wait no. The third is absolute, like the original
`<a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm">Studenten wonen boven azc Stieltjesstraat.webm</a><br>`
vs
`<a href="https://commons.wikimedia.org/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a><br>`
Either `title` attribute changes the behavior or it's `%3A` vs `:`.
I just added two more test cases to https://tools.wmflabs.org/yifeibot/v2ci92.html:
```
  <a href="https://commons.wikimedia.org/wiki/File%3AStudenten_wonen_boven_azc_Stieltjesstraat.webm" title="File:Studenten wonen boven azc Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a><br>
  <a href="https://commons.wikimedia.org/wiki/File:Studenten_wonen_boven_azc_Stieltjesstraat.webm">File:Studenten_wonen_boven_azc_Stieltjesstraat.webm</a><br>
```
Could you test (again)?

**Comment by VDK** [comment]
The top File:Studenten_wonen_boven_azc_Stieltjesstraat.webm link redirects to wikitech wiki and the force download link still forces to download but all other links for

**Comment by zhuyifei1999** [comment]
> but all other links for
Could you clarify? I'm most interested in the behavior of the last two links.

**Comment by VDK** [comment]
those work

**Comment by zhuyifei1999** [comment]
Should hopefully be fixed. Might need to clear the browser cache for the changes to take effect. If the issue persist feel free to reopen.
