### ISSUE TITLE
Hidden characters like \u200b in the title breaks the upload process 

### ISSUE THREAD

**Issue by VDK** [toolforge/video2commons#96]
Please automatically remove these characters:

[\x{00A0}\x{1680}\x{180E}\x{2000}-\x{200B}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}] 

They're blacklisted

**Comment by zhuyifei1999** [comment]
This is supposed to be automatically done by [urlextract.py#L227](https://github.com/toolforge/video2commons/blob/2f78df6a8e4620bd3f8d7a364371ff6ee8243ed4/video2commons/frontend/urlextract.py#L227). Do you have some steps to reproduce a title where it is not properly sanitized?

**Comment by zhuyifei1999** [comment]
What's the url of the video being uploaded? Was the title manually filled or generated?

**Comment by VDK** [comment]
https://www.youtube.com/watch?v=qRhBUpN1c8w

Title was generated

**Comment by zhuyifei1999** [comment]
Confirmed. There's an `\u200b` after 2019​

**Comment by zhuyifei1999** [comment]
U+200B is [zero-width space](https://unicode.org/cldr/utility/character.jsp?a=200B), which [MediaWiki don't think it's bad](https://github.com/wikimedia/mediawiki/blob/d511626236f9eeeb6a55c97c3c0d74d30150dc4f/resources/src/mediawiki/mediawiki.Title.js#L166), but Commons had this [since the regex was added](https://commons.wikimedia.org/w/index.php?title=MediaWiki:Titleblacklist&diff=26929066&oldid=26929014).

**Comment by zhuyifei1999** [comment]
Should be fixed. Feel free to reopen if any other characters are affected.

**Comment by VDK** [comment]
![screenshot_20180203-160357](https://user-images.githubusercontent.com/849603/35768432-094267c2-08fc-11e8-8e97-a6a29a5de9e8.jpg)
I got an error for "⧼titleblacklist-custom-double-apostrophe⧽"
Generated title. The video has since been re-uploaded by the YouTube channel it came from.

**Comment by zhuyifei1999** [comment]
That's the rule `File:.*'{2,}.* <reupload|errmsg=titleblacklist-custom-double-apostrophe>`. Do you suggest replacing `''` it with `"`?

**Comment by VDK** [comment]
Yes

**Comment by zhuyifei1999** [comment]
Should be fixed. Can you test, since I don't know what url the title was generated from?

**Comment by VDK** [comment]
The video that originally had this error was pulled from YouTube by the channel and uploaded slightly different. The new upload also has quotation marks in the title but I'm not sure those are  custom double apostrophes: https://youtu.be/Q-LL_3TdwbA
