### ISSUE TITLE
URLs in the YouTube description are broken/mangled

### ISSUE THREAD

**Issue by legoktm** [toolforge/video2commons#97]
E.g. https://commons.wikimedia.org/w/index.php?title=File:2018_-_Datenschutz_und_die_Daten_der_zu_OpenStreetMap_Beitragenden.webm&oldid=294160297

I noticed this in my uploads too, but manually fixed them. URLs in the description are mangled into `/redirect?...` nonsense.

**Comment by zhuyifei1999** [comment]
Fixed by upgrading youtube_dl on the toolforge side.
